package com.oath.hogs;

import com.google.inject.AbstractModule;
import com.google.inject.Guice;
import com.google.inject.Injector;
import com.oath.hogs.adapter.InputAdapter;
import com.oath.hogs.pipeline.certify.CertifiedEnvironment;
import com.oath.hogs.pipeline.certify.Certifier;
import com.oath.hogs.pipeline.config.Configurator;
import com.oath.hogs.pipeline.config.ConfiguredEnvironment;
import com.oath.hogs.pipeline.generate.GeneratedEnvironment;
import com.oath.hogs.pipeline.generate.Generator;
import com.oath.hogs.pipeline.initialize.InitializedEnvironment;
import com.oath.hogs.pipeline.initialize.Initializer;
import com.oath.hogs.pipeline.validate.ValidatedEnvironment;
import com.oath.hogs.pipeline.validate.Validator;
import com.oath.hogs.serializer.SchemaSerializer;
import graphql.schema.idl.TypeDefinitionRegistry;

/** This Java source file was generated by the Gradle 'init' task. */
public class OlapSchemaGenerator {

  private final Injector injector;

  public OlapSchemaGenerator() {
    this(new DefaultOlapModule().useDefaultBindings());
  }

  public OlapSchemaGenerator(AbstractModule module) {
    this.injector = Guice.createInjector(module);
  }

  public TypeDefinitionRegistry buildTypeDefinitionRegistry(InputAdapter inputAdapter) {

    InitializedEnvironment initializedEnvironment = initialize(inputAdapter.getSourceTypeDefinitionRegistry());

    ConfiguredEnvironment configuredEnvironment = configure(initializedEnvironment);

    ValidatedEnvironment validatedEnvironment = validate(configuredEnvironment);

    GeneratedEnvironment generatedEnvironment = generate(validatedEnvironment);

    CertifiedEnvironment certifiedEnvironment = certify(generatedEnvironment);

    return certifiedEnvironment.getGeneratedTypeDefinitionRegistry();
  }

  public String buildTypeDefinitionString(InputAdapter inputAdapter) {
    return buildTypeDefinitionString(inputAdapter, injector.getInstance(SchemaSerializer.class));
  }

  public String buildTypeDefinitionString(InputAdapter inputAdapter, SchemaSerializer schemaSerializer) {
    return schemaSerializer.serialize(buildTypeDefinitionRegistry(inputAdapter));
  }

  protected InitializedEnvironment initialize(TypeDefinitionRegistry sourceRegistry) {
    Initializer initializer = injector.getInstance(Initializer.class);
    return initializer.initialize(sourceRegistry);
  }

  protected ConfiguredEnvironment configure(InitializedEnvironment initializedEnvironment) {
    Configurator configurator = injector.getInstance(Configurator.class);
    return configurator.configure(initializedEnvironment);
  }

  protected ValidatedEnvironment validate(ConfiguredEnvironment configuredEnvironment) {
    Validator validator = injector.getInstance(Validator.class);
    return validator.validate(configuredEnvironment);
  }

  protected GeneratedEnvironment generate(ValidatedEnvironment validatedEnvironment) {
    Generator generator = injector.getInstance(Generator.class);
    return generator.generate(validatedEnvironment);
  }

  protected CertifiedEnvironment certify(GeneratedEnvironment generatedEnvironment) {
    Certifier certifier = injector.getInstance(Certifier.class);
    return certifier.certify(generatedEnvironment);
  }
}
